/*
 * File: app/view/LadderTabView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.view.LadderTabView', {
    extend: 'Ext.Container',
    alias: 'widget.laddertabview',

    requires: [
        'Coh2Ladder.view.PlayerToolbarSegment',
        'Coh2Ladder.view.DataProviderToolbar',
        'Ext.Toolbar',
        'Ext.SegmentedButton',
        'Coh2Ladder.view.LadderCarousel',
        'Ext.Button',
        'Ext.data.Store'
    ],

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'image',
                        cls: 'coh2org-logo',
                        itemId: 'coh2org-logo',
                        src: 'resources/images/COH2_ORG_logo.png'
                    },
                    {
                        xtype: 'segmentedbutton',
                        itemId: 'gameModeButtons',
                        items: [
                            {
                                xtype: 'button',
                                text: '...'
                            }
                        ]
                    },
                    {
                        xtype: 'playertoolbarsegment'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                cls: 'ladder-header',
                docked: 'top',
                itemId: 'ladderHeader',
                ui: 'light',
                items: [
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'rank'
                        ],
                        html: '#'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'xp'
                        ],
                        html: 'XP'
                    },
                    {
                        xtype: 'component',
                        flex: 3,
                        cls: [
                            'ladder-cell',
                            'player'
                        ],
                        html: '<div>Steam alias</div>'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'wins'
                        ],
                        html: 'W'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'losses'
                        ],
                        html: 'L'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'percentage'
                        ],
                        html: '%'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'streak'
                        ],
                        html: '<div>Streak</div>'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'drops'
                        ],
                        html: '<div>Drops</div>'
                    },
                    {
                        xtype: 'component',
                        flex: 1,
                        cls: [
                            'ladder-cell',
                            'disputes'
                        ],
                        html: '<div>Disputes</div>'
                    }
                ]
            },
            {
                xtype: 'container',
                cls: 'ladder-stack',
                itemId: 'ladderStack',
                layout: {
                    animation: 'flip',
                    type: 'card'
                }
            },
            {
                xtype: 'dataprovidertoolbar'
            }
        ]
    }

});