/*
 * File: app/view/LadderPage.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.view.LadderPage', {
    extend: 'Ext.Container',
    alias: 'widget.ladderpage',

    requires: [
        'Coh2Ladder.view.LadderDataItem',
        'Ext.dataview.List'
    ],

    config: {
        gameModeId: 'gamemode-1v1',
        factionId: 'faction-germans',
        itemId: 'ladderPage1',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'list',
                itemId: 'dataView',
                scrollable: {
                    direction: 'vertical',
                    directionLock: true
                },
                disableSelection: true,
                //defaultType: 'ladderdataitem',
                store: 'emptystore',
                //useComponents: true,
                infinite:true,
                itemTpl: [
                    '<span class="ladder-cell rank">{rank}</span>',
                    '<span class="ladder-cell xp" style="background-image:url(\'{[values.players[0].level_image]}\')">&nbsp;</span>',
                    '<span class="ladder-cell player">{[values.players[0].name]}</span>',
                    '<span class="ladder-cell wins">{wins}</span>',
                    '<span class="ladder-cell losses">{losses}</span>',
                    '<span class="ladder-cell percentage">{percentage}</span>',
                    '<span class="ladder-cell streak{[values.streak > -1 ? " positive" : " negative"]}">{streak}</span>',
                    '<span class="ladder-cell drops">{drops}</span>',
                    '<span class="ladder-cell disputes">{disputes}</span>'
                    ].join('')
            }
        ]
    },

    initialize: function() {
        this.callParent();

        this.getComponent('dataView').setStore({
            model: 'Coh2Ladder.model.Rank',
            sorters: 'rank',
            autoLoad:true
        });

        this.syncStore();
    },

    updateFactionId: function(newValue, oldValue) {
        if (this.initialized)
        this.syncStore();
    },

    updateGameModeId: function(newValue, oldValue) {
        if (this.initialized)
        this.syncStore();
    },

    syncStore: function() {
        //store.load();
    }

});
