/*
 * File: app/view/PlayerView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.view.PlayerView', {
    extend: 'Ext.Container',
    alias: 'widget.playerview',

    requires: [
        'Coh2Ladder.view.PlayerToolbarSegment',
        'Coh2Ladder.view.DataProviderToolbar',
        'Ext.Img'
    ],

    config: {
        cls: 'player-view',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'playertoolbarsegment'
                    },
                    {
                        xtype: 'button',
                        itemId: 'backButton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'image',
                                flex: 1,
                                cls: 'player-avatar',
                                itemId: 'playerAvatar',
                                src: 'http://media.steampowered.com/steamcommunity/public/images/avatars/1a/1afd8afb74217c4a55bc7f629e7e70eac86c7c24_full.jpg'
                            },
                            {
                                xtype: 'image',
                                flex: 1,
                                cls: 'player-level',
                                itemId: 'playerLevelImage',
                                mode: '',
                                src: 'resources/images/levels/rank_18_lieutenant_colonel_class_4.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'vbox'
                        },
                        items: [
                            {
                                xtype: 'component',
                                cls: 'playername',
                                html: 'HelpingHans',
                                itemId: 'playerName'
                            },
                            {
                                xtype: 'component',
                                html: 'XP: 4,558,786',
                                itemId: 'playerXp'
                            },
                            {
                                xtype: 'component',
                                html: 'Lieutenant Colonel Fourth Class (89)',
                                itemId: 'playerLevelText'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container'
            },
            {
                xtype: 'container'
            },
            {
                xtype: 'dataprovidertoolbar'
            }
        ]
    }

});