/*
 * File: app/model/Player.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.model.Player', {
    extend: 'Ext.data.Model',

    uses: [
        'Coh2Ladder.model.Rank'
    ],

    config: {
        fields: [
            {
                name: 'name',
                type: 'string'
            },
            {
                name: 'steam_avatar_url',
                type: 'string'
            },
            {
                name: 'steam_profile_url',
                type: 'string'
            },
            {
                name: 'level',
                type: 'int'
            },
            {
                name: 'experience',
                type: 'int'
            }
        ],
        hasMany: {
            model: 'Coh2Ladder.model.Rank',
            autoLoad: true
        },
        proxy: {
            type: 'memory',
            batchActions: false,
            data: [
                {
                    id: 'player-0',
                    name: 'Qvazar',
                    steam_avatar_url: 'http://media.steampowered.com/steamcommunity/public/images/avatars/e6/e67d1e9ca8a6399421f7f04fd279e33d5bb850f2_full.jpg',
                    steam_profile_url: 'http://steamcommunity.com/profiles/76561198038741197/',
                    level: 74,
                    experience: 2624093
                },
                {
                    id: 'player-1',
                    name: 'AmiPolizeiFunk',
                    steam_avatar_url: 'http://media.steampowered.com/steamcommunity/public/images/avatars/96/967ec7de5b0cc44723fc349f8452b3c46537c165_full.jpg',
                    steam_profile_url: 'http://steamcommunity.com/profiles/76561197993926044/',
                    level: 54,
                    experience: 1224093
                },
                {
                    id: 'player-2',
                    name: 'Sepha',
                    steam_avatar_url: 'http://media.steampowered.com/steamcommunity/public/images/avatars/b0/b054576a4d67fc1e49739c435bbf3b7790043c38_full.jpg',
                    steam_profile_url: 'http://steamcommunity.com/profiles/76561198002889232',
                    level: 56,
                    experience: 1624093
                }
            ],
            reader: {
                type: 'json'
            }
        }
    }
});