/*
 * File: app/model/Rank.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.model.Rank', {
    extend: 'Ext.data.Model',

    uses: [
        'Coh2Ladder.model.Player',
        'Coh2Ladder.model.Faction',
        'Coh2Ladder.model.GameMode'
    ],

    config: {
        fields: [
            {
                name: 'player_id'
            },
            {
                name: 'faction_id'
            },
            {
                name: 'gamemode_id'
            },
            {
                name: 'rank',
                type: 'int'
            },
            {
                name: 'wins',
                type: 'int'
            },
            {
                name: 'losses',
                type: 'int'
            },
            {
                name: 'streak',
                type: 'int'
            },
            {
                name: 'drops',
                type: 'int'
            },
            {
                name: 'disputes',
                type: 'int'
            }
        ],
        belongsTo: {
            model: 'Coh2Ladder.model.Player'
        },
        hasOne: [
            {
                model: 'Coh2Ladder.model.Faction'
            },
            {
                associationKey: 'gamemode_id',
                model: 'Coh2Ladder.model.GameMode'
            }
        ],
        proxy: {
            type: 'memory',
            data: [
                {
                    player_id: 'player-0',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-1v1',
                    rank: 2,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-1v1',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-1v1',
                    rank: 1,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-1v1',
                    rank: 1,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-1v1',
                    rank: 2,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-1v1',
                    rank: 3,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-2v2',
                    rank: 2,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-2v2',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-2v2',
                    rank: 1,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-2v2',
                    rank: 2,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-2v2',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-2v2',
                    rank: 1,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-3v3',
                    rank: 1,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-3v3',
                    rank: 2,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-3v3',
                    rank: 3,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-3v3',
                    rank: 1,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-3v3',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-3v3',
                    rank: 2,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-4v4',
                    rank: 2,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-4v4',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-germans',
                    gamemode_id: 'gamemode-4v4',
                    rank: 1,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                },
                {
                    player_id: 'player-0',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-4v4',
                    rank: 2,
                    wins: 98,
                    losses: 90,
                    streak: -1,
                    drops: 0,
                    disputes: 2
                },
                {
                    player_id: 'player-1',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-4v4',
                    rank: 3,
                    wins: 94,
                    losses: 79,
                    streak: 5,
                    drops: 0,
                    disputes: 1
                },
                {
                    player_id: 'player-2',
                    faction_id: 'faction-soviets',
                    gamemode_id: 'gamemode-4v4',
                    rank: 1,
                    wins: 120,
                    losses: 90,
                    streak: 10,
                    drops: 0,
                    disputes: 3
                }
            ],
            reader: {
                type: 'json'
            }
        }
    }
});