/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coh2Ladder.controller.MainController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "#coh2org-logo": {
                tap: 'openCoh2Org'
            }
        }
    },

    openCoh2Org: function(image, e, eOpts) {
        Ext.device.Device.openURL('http://www.coh2.org/');
    }

});